# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build

  script:
    - dotnet restore --source ~/cts_local_nuget
    - dotnet publish -c Release --no-restore
    - cd bin/Release/net7.0/
    - tar cvfz ~/publish.tgz publish 
    - printf 'krish@Nic24\ny'|/opt/cisco/anyconnect/bin/vpn -s connect sconnect.nic.in
    - scp ~/publish.tgz root@10.173.13.51:/home/www-data/cts
    - ssh root@10.173.13.51 "systemctl stop ctsapi.service && cd /home/www-data/cts/ && rm -rf publish && tar xvfz publish.tgz && rm publish.tgz && chown -R 1000:1000 publish && chmod -R 755 publish && systemctl daemon-reload && systemctl start ctsapi.service"
    - /opt/cisco/anyconnect/bin/vpn disconnect
