# Reference: https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0

@PensionAPI_HostAddress = http://api.{{$dotenv PROJECT_BASE_URL}}
@accessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvbiI6IntcIklkXCI6MyxcIk5hbWVcIjpcIkNUU1wiLFwiTGV2ZWxzXCI6W3tcIklkXCI6OCxcIk5hbWVcIjpcIlRyZWFzdXJ5XCIsXCJTY29wZVwiOltcIkJBQVwiXX1dLFwiUm9sZXNcIjpbe1wiSWRcIjoxNyxcIk5hbWVcIjpcIkRUQVwiLFwiUGVybWlzc2lvbnNcIjpbXCJjYW4tY2hlcXVlLWVudHJ5XCIsXCJjYW4tYXBwcm92ZS1yZWplY3QtY2hlcXVlLWluZGVudFwiLFwiY2FuLWNyZWF0ZS1pbmRlbnQtaW52b2ljZVwiXX1dfSIsIm5hbWVpZCI6IjQ4IiwibmFtZSI6IkNUUyBCQUEgIERUQSIsIm5iZiI6MTcwNzMwNTU0MiwiZXhwIjoxNzA3MzkxOTQyLCJpYXQiOjE3MDczMDU1NDJ9.EHTX3KpHuOiuCaM7Cz0UOrTyfTegdOi8p64Dos0oa1Im-kz1mNSCqCyAhvOyPMTY1zFzOAGJj8svsq88hdrHdQ
# {{Login.response.body.$.accessToken}}

@refreshToken = {{Login.response.body.$.refreshToken}}


@treasuryReceiptNo = {{CreatePPOReceipt.response.body.$.result.treasuryReceiptNo}}

@ApprovedPpoId = {{SetApprovePPOFlag.response.body.$.result.ppoId}}
@ApprovedPpoIdStatusFlag = {{SetApprovePPOFlag.response.body.$.result.statusFlag}}

### Approve PPO
# @name SetApprovePPOFlag
POST {{PensionAPI_HostAddress}}/api/v1/ppo/status
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "PpoId": "{{$randomInt 10000 99999}}",
  "StatusFlag": 1,
  "StatusWef": "{{$datetime "YYYY-MM-DD"}}"
}

### Reject Approved PPO
# @name ClearApprovePPOFlag
DELETE {{PensionAPI_HostAddress}}/api/v1/ppo/{{ApprovedPpoId}}/status/{{ApprovedPpoIdStatusFlag}}
Accept: application/json
Authorization: Bearer {{accessToken}}


### Check PPO Status Flag
# @name CheckPPOFlag
Get {{PensionAPI_HostAddress}}/api/v1/ppo/{{ApprovedPpoId}}/status
Accept: application/json
Authorization: Bearer {{accessToken}}



### Read PPO Receipt Request
# @name GetPPOReceipt
GET {{PensionAPI_HostAddress}}/api/v1/manual-ppo/receipts/{{treasuryReceiptNo}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### List All PPO Receipts Request
# @name GetAllManualPPOReceipts
PATCH {{PensionAPI_HostAddress}}/api/v1/manual-ppo/receipts
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{"pageSize":10,"pageIndex":0,"filterParameters":[],"sortParameters":{"field":"","order":""}}

### Create PPO Receipt Request
# @name CreatePPOReceipt
POST {{PensionAPI_HostAddress}}/api/v1/manual-ppo/receipts
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "ppoNo": "PPO-{{$randomInt 100000 999999}}",
  "pensionerName": "Jack Dowsel",
  "dateOfCommencement": "2024-07-15",
  "mobileNumber": "{{$randomInt 6000000000 9999999999}}",
  "receiptDate": "{{$datetime "YYYY-MM-DD"}}",
  "psaCode": "A",
  "ppoType": "N"
}

### Update PPO Receipt Request
# @name UpdatePPOReceipt
PUT {{PensionAPI_HostAddress}}/api/v1/manual-ppo/receipts/{{treasuryReceiptNo}}
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "ppoNo": "PPO-{{$randomInt 100000 999999}}",
  "pensionerName": "Jack Smith",
  "dateOfCommencement": "2024-07-19",
  "mobileNumber": "{{$randomInt 6000000000 9999999999}}",
  "receiptDate": "{{$datetime "YYYY-MM-DD"}}",
  "psaCode": "A",
  "ppoType": "N"
}








### Echo Request
# @name CreateManualPPOReceipt
POST {{PensionAPI_HostAddress}}/api/v1/echo
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "treasuryReceiptNo": "{{@treasuryReceiptNo}}",
  "ppoNo": "PPO-{{$randomInt 100000 999999}}",
  "pensionerName": "Jack Dowsel",
  "dateOfCommencement": "2024-07-15",
  "mobileNumber": "{{$randomInt 6000000000 9999999999}}",
  "receiptDate": "{{$datetime "YYYY-MM-DD"}}",
  "psaCode": "P",
  "ppoType": "N"
}

### Get DateOnly Request
# @name GetDateOnly
GET {{PensionAPI_HostAddress}}/api/v1/date-only
Accept: application/json
Authorization: Bearer {{accessToken}}


### Set DateOnly Request
# @name SetDateOnly
POST {{PensionAPI_HostAddress}}/api/v1/date-only
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dateOnly": "{{$datetime "YYYY-MM-DD" -5 d}}"
}


### WeatherForecast Request
# @name GetWeatherForecast
GET {{PensionAPI_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{accessToken}}

### Register User
# @name Register
POST {{PensionAPI_HostAddress}}/auth/register/
Content-Type: application/json

{
  "email": "sns@example.com",
  "password": "P@ssw0rd"
}

### Login Request
# @name Login
POST {{PensionAPI_HostAddress}}/auth/login/
Content-Type: application/json

{
  "email": "sns@example.com",
  "password": "P@ssw0rd"
}

### RefreshToken Request
# @name RefreshToken
POST {{PensionAPI_HostAddress}}/auth/refresh/
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}