namespace CTS_BE.Model.Pension
{
  public class PensionerDetailsModel
  {
    public int IntPensionerId { get; set; }
    public int? IntGpfNoIdObs { get; set; }
    public int? IntDistrictIdObs { get; set; }
    public string? SubscrFirstName { get; set; }
    public string? SubscrMiddleName { get; set; }
    public string? SubscrLastName { get; set; }
    public int? IntRelIdObs { get; set; }
    public DateOnly DateOfBirth { get; set; }
    public DateOnly? DateOfExit { get; set; }
    public DateOnly? RetirementDate { get; set; }
    public string? EmpGenderObs { get; set; }
    public int? IntMaritalStatusId { get; set; }
    public int? IntReligionId { get; set; }
    public int? IntNationalityId { get; set; }
    public string? MobileNumber { get; set; }
    public string? EmailId { get; set; }
    public string? IdentificationMark { get; set; }
    public int? IntIdentityTypeIdObs { get; set; }
    public string? IdentityCardNumberObs { get; set; }
    public string? IfscCode { get; set; }
    public string? BankAcNo { get; set; }
    public int? HeightInCenti { get; set; }
    public int? IntPayableTreaIdPenObs { get; set; }
    public int? IntDdoId { get; set; }
    public string? CvpOptedFlag { get; set; }
    public int? CvpPercentage { get; set; }
    public string? PCityVillageObs { get; set; }
    public string? PTownObs { get; set; }
    public string? PPoliceStationObs { get; set; }
    public string? PDistrictCodeObs { get; set; }
    public int? PStateObs { get; set; }
    public string? PPinObs { get; set; }
    public string? CCityVillageObs { get; set; }
    public string? CTownObs { get; set; }
    public string? CPoliceStationObs { get; set; }
    public string? CDistrictCodeObs { get; set; }
    public int? CStateObs { get; set; }
    public string? CPinObs { get; set; }
    public int? PenFileId { get; set; }
    public int? LastPostIdObs { get; set; }
    public int? InstituteIdObs { get; set; }
    public int? SendToUserIdObs { get; set; }
    public char ActiveFlag { get; set; }
    public int ProcessingFlag { get; set; }
    public int? PrevIntPensionerId { get; set; }
    public string? IdentificationMark2 { get; set; }
    public string? PanNo { get; set; }
    public char FinalGpfAppliedFlag { get; set; }
    public DateOnly? FinalGpfAppliedDate { get; set; }
    public string? ReasonFinalGpfNotApply { get; set; }
    public char? PreviousPensionType { get; set; }
    public char? PreviousPensionSource { get; set; }
    public string? PreviousPensionPpoNo { get; set; }
    public int? PreviousPensionAmt { get; set; }
    public DateOnly? PreviousPensionWef { get; set; }
    public string? FinalGpfAppliedLetterNo { get; set; }
    public string? BsrCode { get; set; }
    public string? HrmsEmpIdObs { get; set; }
    public char DeclrnCheckFlag { get; set; }
    public int DmlStatusFlag { get; set; }
    public int UserId { get; set; }
    public DateTime? CreatedTimestamp { get; set; }
    public int ModifiedUserId { get; set; }
    public DateTime? ModifiedTimestamp { get; set; }
    public int? PrevIntTreasuryId { get; set; }
    public string? PrevBankIfscCode { get; set; }
    public string? PrevPia { get; set; }
    public string? EduQualificationObs { get; set; }
    public string? TrainingObs { get; set; }
    public int? PenTypeId { get; set; }
    public string? SalutationNameOfRelativeOb { get; set; }
    public string? FirstNameOfRelativeObs { get; set; }
    public string? MiddleNameOfRelativeObs { get; set; }
    public string? LastNameOfRelativeObs { get; set; }
    public int? IntDesignationId { get; set; }
    public int? IntPostId { get; set; }
    public string? PensionFileNo { get; set; }
    public string? DesignationDesc { get; set; }
    public string? PostDesc { get; set; }
    public int? IntCadreId { get; set; }
    public string? CadreDesc { get; set; }
    public int? IntSrvId { get; set; }
    public string? ServiceTypeDesc { get; set; }
    public int? IntEmploymentType { get; set; }
    public string? EmploymentTypeDesc { get; set; }
    public string? TreasuryCodePayable { get; set; }
    public int? IntEmployeeId { get; set; }
    public string? EmployeeNo { get; set; }
    public int? RequestId { get; set; }
    public string? TresCodePayableOutState { get; set; }
    public string? WbHealthSchemeFlag { get; set; }
    public string? HealthSchemeToBeContinued { get; set; }
    public string? MemberOfGpf { get; set; }
    public string? GpfSeries { get; set; }
    public string? GpfSeries1 { get; set; }
    public string? GpfAccountNo { get; set; }
    public int? IntHeadOfOfficeId { get; set; }
    public int? IntAppAuthorityId { get; set; }
    public string? FromEss { get; set; }
    public int? IntPrepDeclarationId { get; set; }
    public string? BankObs { get; set; }
    public string? BranchNameObs { get; set; }
    public int? BenfTypeId { get; set; }
    public int? EmpIntOmiGender { get; set; }
    public string? MaritalStatusDesc { get; set; }
    public string? ReligionDesc { get; set; }
    public string? GenderDesc { get; set; }
    public int? IntPayableTreaIdGratObs { get; set; }
    public string? SalutationNameOfEmplObs { get; set; }
    public string? PayableTreasuryFlag { get; set; }
    public string? PayableOutTreasuryName { get; set; }
    public int? RoleId { get; set; }
    public int? ModifiedRoleId { get; set; }
    public DateOnly? ApplicationDate { get; set; }
    public int? RetirementForeAftNoon { get; set; }
    public string? Nationality { get; set; }
    public int? IntDeptId { get; set; }
    public string? DeptDescription { get; set; }
    public int? IntSanctioningAuthorityId { get; set; }
    public string? SanctioningAuthorityType { get; set; }
    public string? AppointmentAddHocFlag { get; set; }
    public string? PreviousCvpApplicationFlag { get; set; }
    public string? PreviousCvpAppliRemarks { get; set; }
    public string? PrevAppearanceMedicalFlag { get; set; }
    public string? PrevAppearMedicalRemarks { get; set; }
    public string? PpoNumber { get; set; }
    public int? IntPostCode { get; set; }
    public string? PostCode { get; set; }
    public string? ForwardingAuthorityObs { get; set; }
    public int? IntServiceBookAvail { get; set; }
    public string? CourtCasePendingStatus { get; set; }
    public string? CourtCaseRemarks { get; set; }
    public int? ApproverUserId { get; set; }
    public int? ApproverRoleId { get; set; }
    public DateTime? ApproveTimeStamp { get; set; }
    public DateOnly? DateOfJoining { get; set; }
    public int? PenSanctionIntTreasuryId { get; set; }
    public int? IntOmiPfNpsType { get; set; }
    public string? PsaCode { get; set; }
    public string? ReEmployedAftRetirRemarks { get; set; }
    public string? FamilyPensionerEmployedFlag { get; set; }
    public string? FamilyPenEmployedRemarks { get; set; }
    public string? FamilyPenRcptPenRemarks { get; set; }
    public string? CpfShareRemarks { get; set; }
    public string? ProvisionalPensionRemarks { get; set; }
    public string? ProvisionalGratuityRemarks { get; set; }
    public string? AppointmentAddHocRemarks { get; set; }
    public string? OtherPensionReceiptFlag { get; set; }
    public string? OtherPensionRcptName { get; set; }
    public string? OtherPensionRcptParticular { get; set; }
    public string? OtherPensionRcptSource { get; set; }
    public string? VigilanceCasePendingRemarks { get; set; }
    public string? DeptCriminalProcRemarks { get; set; }
    public string? ReEmployedAfterRetireFlag { get; set; }
    public string? FamilyPenRcptOthPenFlag { get; set; }
    public string? ProvisionalPenReceivedFlag { get; set; }
    public string? ProvisionalGratuityRcvdFlag { get; set; }
    public string? VigilanceCasePendingFlag { get; set; }
    public string? DeptCriminalProcPendingFlg { get; set; }
    public string? TresNamePayableOutState { get; set; }
    public int? TresCodePayableOutStateId { get; set; }
    public string PsaTreasuryModifiableFlag { get; set; } = null!;
    public string? IntPsaTreasuryCode { get; set; }
    public int? IntHeadOfOfficeIdSb { get; set; }
    public string? PsaDdoAvlFlag { get; set; }
    public string? OtherPpoNo { get; set; }
    public string? OtherPpoDetails { get; set; }
    public string? WritPetitionNo { get; set; }
    public string? WritPetitionDetails { get; set; }
    public string? ProcessingStageDtl { get; set; }
    public int? IntOmiCourtCaseType { get; set; }
    public string? CourtCaseType { get; set; }
    public string? CourtCaseNo { get; set; }
    public int? CourtCaseYear { get; set; }
    public string? NameOfCourt { get; set; }
    public int? IntOmiCaseStatus { get; set; }
    public int? IntOmiCaseRelationTo { get; set; }
    public string? CaseRelOtherReason { get; set; }
    public string? NameOfTheAuthority { get; set; }
    public string? Remarks { get; set; }
    public string? PensionTypeFlag { get; set; }
    public string? PensionCalcType { get; set; }
    public int? IntPsaDdoId { get; set; }
    public string? ProvPenSystemRcvdFlag { get; set; }
    public string? ProvGratSystemRcvdFlag { get; set; }
    public int? RateOfProvPension { get; set; }
    public string? ProvPensionPeriod { get; set; }
    public int? RateOfProvGratuity { get; set; }
    public string? GratuityPaymentOrderNo { get; set; }
    public string? CommutedValuePayOrderNo { get; set; }
    public string? ApprovalAuthDesignation { get; set; }
    public int? IntSpouseReligionId { get; set; }
    public int? IntPsaDesignationId { get; set; }
    public string? PsaAddress { get; set; }
    public string? TreasuryBank { get; set; }
    public string? TreasuryName { get; set; }
  }
}