name: DotNet CI

on: [push]

jobs:
  database:
    name: Setup Database
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout IFMS-CTS repository for branch selection
        uses: actions/checkout@v4
        with:
          repository: "abusalam/IFMS-CTS"

      - name: Select Branch of IFMS-CTS repository
        id: selected-branch
        run: |
          if [[ -n $(git ls-remote --heads origin ${{ github.head.ref || github.ref }}) ]]; then
            echo "branch-name=${{ github.head.ref || github.ref }}" >> $GITHUB_OUTPUT
          fi

    outputs:
      branch-name: ${{ steps.selected-branch.outputs.branch-name }}

  build:
    name: Build DotNet
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout DotNet repository
        uses: actions/checkout@v4

      - name: Verify Code Formatting
        run: |
          dotnet tool restore
          dotnet csharpier --check .

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          # cache: true
      - name: Install dependencies & Build DotNet
        run: |
          git show --oneline -s
          dotnet restore
          dotnet build

  test:
    name: Test DotNet
    needs: [build, database]
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout IFMS-CTS repository
        uses: actions/checkout@v4
        with:
          repository: "abusalam/IFMS-CTS"
          ref: ${{ needs.database.outputs.branch-name }}
          submodules: "recursive"

      - name: Start Backend Database Server
        run: |
          cp .env.docker .env
          sudo echo "127.0.0.1 postgres" | sudo tee -a /etc/hosts
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose up -d postgres

      - name: Run xUnit Tests
        run: |
          echo "IFMS-CTS Branch: ${{ needs.database.outputs.branch-name }}"
          git show --oneline -s
          cd dotnet/CTS-BE
          echo "dotnet/CTS-BE Current Commit: On Branch: ${{ github.ref_name }}"
          git show --oneline -s
          cd ../..
          SUBMODULE_PATH="dotnet/CTS-BE"
          git submodule foreach --recursive "if [ \$path = '$SUBMODULE_PATH' ]; then git fetch origin \${{ github.ref_name }}; git checkout origin/\${{github.ref_name }}; fi"
          cd dotnet/CTS-BE
          echo "dotnet/CTS-BE Updated Commit:"
          # git checkout --progress --force ${{ github.head.ref || github.ref }}
          # echo "dotnet/CTS-BE Branch: ${{ github.head.ref || github.ref }}"
          git show --oneline -s
          cd ..
          dotnet test --logger trx --results-directory "TestResults-8.x"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-8.x
          path: dotnet/TestResults-8.x
          # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
